replicaCount: 1

image:
  repository: jcorral/ecr-credentials-controller
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext:
  capabilities:
     drop:
     - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  cpu: 100m
  memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: {}
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""
